README.md
pom.xml

Upgraded to Elide 4.6.1

---

pom.xml

Upgrading to Elide 4.6.2

---

src/main/java/example/Settings.java
src/main/resources/dbconfig.properties

Added hibernate batch fetching by default to configuration

---

README.md
pom.xml
src/main/java/example/Settings.java
src/main/java/example/models/ArtifactGroup.java
src/main/java/example/models/ArtifactProduct.java
src/main/java/example/models/ArtifactVersion.java
src/main/resources/analytics/models/tables/artifactDownloads.hjson
src/main/resources/db/changelog/changelog.xml
src/test/java/example/ExampleTest.java

Add analytic model

---

pom.xml
src/main/java/example/Settings.java
src/main/java/example/models/ArtifactGroup.java
src/main/java/example/models/ArtifactProduct.java
src/main/java/example/models/ArtifactVersion.java
src/main/resources/analytics/models/tables/artifactDownloads.hjson
src/test/java/example/ExampleTest.java

postgres support

---

Procfile
pom.xml
src/main/java/example/Main.java

Update database using liquibase cli option in release mode.

Update database using liquibase cli option in release mode.

---

pom.xml

UpgradeElide4Version

---

pom.xml
src/main/java/example/Settings.java

Added setting to enable / disable MetaDataStore.

metadatastore disabled

---

pom.xml
src/main/java/example/Settings.java
src/main/resources/analytics/models/tables/artifactDownloads.hjson
src/main/resources/db/changelog/changelog.xml

ResponseBody as LOB/Text

---

pom.xml
src/main/java/example/Settings.java
src/main/resources/analytics/models/tables/artifactDownloads.hjson
src/main/resources/db/changelog/changelog.xml

Export Async Support

---

src/main/java/example/Settings.java
src/main/resources/dbconfig.properties

Removing hibernate validation

---

pom.xml
src/main/java/example/models/ArtifactGroup.java
src/main/java/example/models/ArtifactProduct.java
src/main/java/example/models/ArtifactVersion.java
src/main/resources/analytics/models/tables/artifactDownloads.hjson

Upgrading to elide 5.0

---

pom.xml

Bumping to Elide 5.0.1

---

pom.xml

Upgrading to Elide 5.0.9

---

README.md
screwdriver.yaml

Migrate to Screwdriver

---

.travis.yml

Remove Travis yml file as we migrated to Screwdriver

---

pom.xml
screwdriver.yaml
src/main/java/example/Main.java
src/main/java/example/Settings.java
src/main/java/example/models/ArtifactGroup.java
src/main/resources/META-INF/resources/graphiql/subscription.html
src/main/resources/META-INF/resources/index.html
src/test/java/example/ExampleTest.java
src/test/java/example/IntegrationTest.java
system.properties

GraphQL subscriptions

---

Code-Of-Conduct.md
pom.xml
src/main/java/example/Main.java
src/main/java/example/Settings.java
src/main/java/example/filters/CorsFilter.java
src/main/java/example/models/ArtifactGroup.java
src/main/java/example/models/ArtifactProduct.java
src/main/java/example/models/ArtifactVersion.java
src/main/resources/META-INF/resources/index.html
src/test/java/example/ExampleTest.java
src/test/java/example/IntegrationTest.java

Change Verizon Media to Yahoo

---

pom.xml

Upgrading to Elide 6.0.1

---

pom.xml

Updating Elide to 6.1.4

---

src/main/resources/META-INF/resources/graphiql/LICENSE
src/main/resources/META-INF/resources/graphiql/index.html
src/main/resources/META-INF/resources/graphiql/subscription.html

Upgrade graphiql to version 3.0.2

---

src/main/resources/logback.xml

Fix jpql logging

---

pom.xml
src/main/java/example/Settings.java

Upgrade elide from 7.0.0 to 7.1.0
